### PR TITLE
Updated the gateway-controller-role ClusterRole permissions

### PR DESCRIPTION
**Pull request by Chimbu-DoiT**
This PR is to update the gateway-controller-role ClusterRole permissions as reported in https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/issues/68

### CODE REVIEW

**Comment by Philipp-Plotnikov** [comment]
Thanks. Could you please fix DCO? https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md

**Comment by Philipp-Plotnikov** [comment]
@Chimbu-DoiT ping me when you will fix it, please. I will approve and merge. Thank you for contribution!

**Comment by Chimbu-DoiT** [comment]
HI @Philipp-Plotnikov I have fixed DCO

**Review by Philipp-Plotnikov — APPROVED** [review]

**Comment by Philipp-Plotnikov** [comment]
Great work @Chimbu-DoiT !

**Pull request merged**
